### PR TITLE
feat: allow index name with placeholders for orgId or and/or envId

### PR DESCRIPTION
**Pull request by aurelien-pacaud**
**Issue**

https://gravitee.atlassian.net/browse/CJ-1757

**Description**

Allow placeholder in elasticsearch index name

---
**Gravitee.io Automatic Deployment**

🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
 - use it directly by updating your project with version: `6.0.0-placeholder-index-SNAPSHOT`
 - download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/6.0.0-placeholder-index-SNAPSHOT/gravitee-common-elasticsearch-6.0.0-placeholder-index-SNAPSHOT.zip)

### CODE REVIEW

**Comment by gcusnieux** [comment]
You've changed the method signature, so maybe we should add a BREAKING CHANGE to create a major version.

**Review by jhaeyaert — APPROVED** [review]
LGTM 👍

**Comment by jhaeyaert** [comment]
> You've changed the method signature, so maybe we should add a BREAKING CHANGE to create a major version.

Yes, you are right! It should be considered as a BC. Well spotted 👍

**Pull request merged**
